# * Script to update code on AWS EC2 ubuntu, script for continuous deploy.
name: CD Pipeline

# * Runs only after the CI script finishes with success status.
on:
  workflow_run:
    workflows: ["CI Pipeline"] 
    types:
      - completed 

jobs:
  deploy:
    runs-on: ubuntu-24.04  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Access AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Access with SSH to EC2 Instance and execute the commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_UBUNTU_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        port: 22
        script: |

          # Search path of project and adjusting the permissions of user:
          cd /var/www/html/API_TEST_PHP
          sudo chown -R $USER:$USER .
          
          # Update the code:
          git clean -fd
          git reset --hard
          git pull origin main
          
          # composer run base:prod
          # composer run migration:prod
          # composer run update:autoload

          # Restart the services of server:
          # sudo systemctl restart php8.2-fpm
          # sudo systemctl restart nginx

          # Restore the permissions for web server:
          sudo chown -R www-data:www-data .
          # sudo chmod -R 755 /var/www/html/API_TEST_PHP

          echo "🚀 Deploy concluído com sucesso!"
