# * Script to update code on AWS EC2 ubuntu, executed only if CI has success status, script of continuous deploy.

name: CD Pipeline

# * Runs only after the CI script finishes with success status.
on:
  workflow_run:
    workflows: ["CI Pipeline"] 
    types:
      - completed 

jobs:
  deploy:
    runs-on: ubuntu-24.04  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Access AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Access with SSH to EC2 Instance
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.AWS_UBUNTU_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        port: 22

    - name: Access the folder of projects and Cloning the repository of project
      run: | 
        cd /var/www/html
        git clone https://github.com/R1TKILL/API_TEST_PHP.git   

    - name: Access the folder of API and Config the project
      run: | 
        cd /var/www/html/API_TEST_PHP
        composer run base:prod
        composer run migration:prod

    - name: Restart the NGINX and PHP-FPM
      run: |
        sudo systemctl restart php8.2-fpm
        sudo systemctl restart nginx

    - name: Verify Deployment
      run: |
        curl -f http://${{ secrets.PROD_HOST }}/api/pessoa/items || exit 1

